winzou_state_machine:
    app_supplier:
        class: "%app.model.supplier.class%"
        property_path: state
        graph: app_supplier
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            trusted: ~
        transitions:
            trust:
                from: [new]
                to: trusted
        callbacks:
            after:
                notify:
                    on: ['trust']
                    do: ['@App\Notifier\SupplierTrustingNotifierInterface', 'notify']
                    args: ['object']
